### ISSUE TITLE
UI-, UX-Design

### ISSUE THREAD

**Issue by SamaraDominik** [mercal03/TINF21C_Team1_AAS-Server-Webclient#14]

**Comment by SamaraDominik** [comment]
![image](https://user-images.githubusercontent.com/114293530/224273520-eb249855-fb05-45e5-86e5-6f6f746ceef3.png)
![image](https://user-images.githubusercontent.com/114293530/224273556-58877f36-0e1d-4f2f-998f-e827aa71e8c9.png)

**Comment by SamaraDominik** [comment]
Designentwurf Stand 10.03

**Comment by SamaraDominik** [comment]
![image](https://user-images.githubusercontent.com/114293530/224279986-c3324330-092a-4e1e-9e04-3b73794676a0.png)
![image](https://user-images.githubusercontent.com/114293530/224280568-a98bf1e1-0f95-45aa-b36d-e35d3fb34fa2.png)

**Comment by mrentsch65** [comment]
Vielleicht noch folgende Usability-Verbesserung: Anstatt des separaten Buttons "Open Asset" würde ich einfach die ganze Zeile anklickbar machen:
![image](https://user-images.githubusercontent.com/50681355/225850474-b9f0d5ea-5be1-40cb-b8ba-e6c22af3dad7.png)

**Comment by mrentsch65** [comment]
Der Name linksbündig würde besser aussehen und es fehlt eine Versions-Info bzw. das Builddate:
![image](https://user-images.githubusercontent.com/50681355/231830881-90b4bf33-2fa4-4db2-8640-e07bb843f99e.png)
