### ISSUE TITLE
Angebotenener Server "localhost" funktioniert nicht im Preview über das Internet

### ISSUE THREAD

**Issue by mrentsch65** [mercal03/TINF21C_Team1_AAS-Server-Webclient#18]
![image](https://user-images.githubusercontent.com/50681355/225844224-a259bd07-fca8-403a-8c56-aa8a502f32aa.png)

Die hier tun prinzipiell: 
https://admin-shell-io.com/5001/shells
https://v3.admin-shell-io.com/shells
nehmen Sie die am Besten als Default-Server

Allerdings ist die Anzeige der Inhalte nicht immer korrekt und die Bilder werden nicht angezeigt:

![image](https://user-images.githubusercontent.com/50681355/225845038-c3af2eb9-cc8b-4446-87e2-fb7ebecfe877.png)

**Comment by mercal03** [comment]
Haben sie ein Plugin installiert, dass CORS ausschaltet?

**Comment by mrentsch65** [comment]
Ja, CORS-Plugin ist aktiv.

**Comment by mrentsch65** [comment]
Haben Sie das CORS-Plugin bei sich installiert?

**Comment by mrentsch65** [comment]
Jetzt geht überhaupt nichts mehr: 
Website Preview: https://f0b3c497-4d15-48ec-bc83-8d486e734486.ma.bw-cloud-instance.org/
Alternativlink: http://193.196.55.115/

**Comment by mercal03** [comment]
Die Bwcloud Server wurden gewartet und ich musste den Server manuell neustarten. Jetzt sollte es wieder gehen.

**Comment by mrentsch65** [comment]
Ja, geht wieder, allerdings lassen sich diese Server nicht connecten: 
https://admin-shell-io.com/5001/shells
https://v3.admin-shell-io.com/shells

**Comment by mercal03** [comment]
Ich habe es jetzt gefixt. Beide Server können geladen werden. Mit den Icons gibt es allerdings noch Probleme.

**Comment by mrentsch65** [comment]
Ich schaffe es nicht, diesen Server in Ihrer App zu zu connecten:

http://aas.murrelektronik.com:4000/registry

Hier tut er:
![image](https://user-images.githubusercontent.com/50681355/232048737-46295e8a-9951-4e46-a5d1-95c17819c192.png)
